aws_region    = "us-east-1"
environment   = "dev"
vpc_cidr      = "10.0.0.0/16"
project_name  = "real-production-project"
instance_type = "t2.medium"
key_name      = "Docker-keys"
db_name       = "appdb"
db_username   = "appuser"
db_password   = "CHANGE_PASSWORD"

